
import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME } from "../constants";

export const generateProfessionalPortrait = async (
  base64Image: string,
  customPrompt: string
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing. Please ensure process.env.API_KEY is configured.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Strip the prefix if it exists (e.g., data:image/jpeg;base64,)
  const base64Data = base64Image.replace(/^data:image\/(png|jpeg|webp);base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: "image/jpeg",
            },
          },
          {
            text: customPrompt,
          },
        ],
      },
    });

    let generatedImageUrl = "";
    
    // Check candidates for image data
    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!generatedImageUrl) {
      // Sometimes the model returns text explaining why it couldn't generate or it might have just text output
      if (response.text) {
          throw new Error(`Model response: ${response.text}`);
      }
      throw new Error("No image was generated by the model. This might be due to safety filters or model limitations.");
    }

    return generatedImageUrl;
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "An error occurred while generating the image.");
  }
};
